---
- name: setting up mysql database
  hosts: DATABASES
  become: true
  vars_files:
    - vars/database.yml

  tasks:
  - name: Install mysql Package
    apt: 
     name: '{{ item }}'
     update_cache: yes 
     state: latest
    with_items:
        - mysql-client
        - python3-dev
        - libmysqlclient-dev
        - python3-mysqldb
        - python-pip

  - name: Install MySQL-python
    pip: 
      name: MySQL-python

  - name: Sets the root password
    mysql_user:
      name: root
      password: "{{ root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Removes all anonymous user accounts
    mysql_user:
     name: ''
     host_all: yes
     state: absent
     login_user: root
     login_password: "{{ root_password }}"

  - name: Removes the MySQL test database
    mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ root_password }}"